<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net8.0;net472;netstandard2.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0' Or '$(TargetFramework)' == 'net8.0'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.Owin" Version="4.2.3" />
    <PackageReference Include="Microsoft.Owin.Cors" Version="4.2.3" />
    <PackageReference Include="Microsoft.AspNet.Cors" Version="5.3.0" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net472'">
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <DefineConstants>$(DefineConstants);LEGACY_OWIN</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0' Or '$(TargetFramework)' == 'net8.0'">
    <DefineConstants>$(DefineConstants);ASPNETCORE</DefineConstants>
  </PropertyGroup>

</Project>